######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 1 11:48:31 2010
######################################################################
QT +=network
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Base64.h faxtomailmodule.h mainwindow.h smtp.h
FORMS += mainwindow.ui
SOURCES += Base64.cpp faxtomailmodule.cpp main.cpp mainwindow.cpp smtp.cpp
