######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 28 18:22:40 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += faxtomailmodule.h mainwindow.h \
    smtp.h
FORMS += mainwindow.ui
SOURCES += faxtomailmodule.cpp main.cpp mainwindow.cpp \
    smtp.cpp
